name: Run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version-file: .nvmrc

      - name: Installing dependencies
        run: npm install

      - name: Linter Validation
        run: npm run eslint

      - name: Pull and Configure TCP Server
        run: docker run -d -p 9950:9950 -p 9528:9528 cameritelabs/tcp-receiver:latest

      - name: Run tests
        run: npm run test
